[[main]]
  name = "Home"
  url = ""
  weight = -110

[[main]]
  name = "Archives"
  url = "posts/"
  weight = -109

# Submenus are done this way: parent -> identifier
#[[main]]
#  name = "Links"
#  identifier = "Links"
#  weight = -108
#[[main]]
#  parent = "Links"
#  name = "LinkedIn"
#  url = "https://www.linkedin.com/"
#[[main]]
#  parent = "Links"
#  name = "Twitter"
#  url = "https://twitter.com/"

[[main]]
  name = "About"
  url = "about/"
  weight = -107

[[main]]
name = "Impressum"
url = "https://soebes.io/impressum/"
weight = -107

# social menu links

[[social]]
  name = "github"
  type = "social"
  weight = 1
  url = "https://github.com/khmarbaise"
[[social]]
  name = "mastodon"
  weight = 2
  url = "https://mastodon.social/@khmarbaise"
[[social]]
  name = "youtube"
  weight = 3
  url = "https://youtube.com/@khmarbaise"
[[social]]
  name = "bluesky"
  url = "https://bsky.app/profile/khmarbaise.bsky.social"
  weight = 4
[[social]]
  name = "linkedin"
  weight = 5
  url = "https://www.linkedin.com/in/karl-heinz-marbaise-17a15614"
[[social]]
  name = "instagram"
  weight = 6
  url = "https://www.instagram.com/khmarbaise/"
[[social]]
  name = "rss"
  weight = 7
  url = "index.xml"
#[[social]]
#  name = "twitter"
#  weight = 10
#  url = "https://twitter.com/khmarbaise"

# other supported social links
# name = "youtube"
# url = "https://www.youtube.com/#"
# name = "facebook"
# url = "https://facebook.com/#"
# name = "instagram"
# url = "https://instagram.com/#"
# name = "stackoverflow"
# url = "https://stackoverflow.com/#"
# name = "gitlab"
# url = "https://gitlab.com/#"
# name = "discord"
# url = "https://discord.gg/#"